#Data source configuration
spring:
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/jgaceSky?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: jgaceSky
    password: quanjinshutiankong
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 5 # 初始化连接数
      minIdle: 5 # 最小空闲连接数
      maxActive: 20 # 最大连接数
      testOnBorrow: true # 从连接池中取出连接时是否测试连接的可用性
      validationQuery: SELECT 1 # 测试连接可用性的SQL
    #rabbitMq configuration
#    rabbitmq:
#      host: localhost
#      port: 5672
#      username: guest
#      password: guest


    #Redis configuration
    redis:
      host: 192.168.1.102
      port: 6379
      password: 7355608

    #xxlJob configuration
#    xxl:
#      job:
#        admin:
#          addresses: http://localhost:8080/xxl-job-admin
#        accessToken:
#        executor:
#          appname: xxl-job-executor-sample-springboot
#          ip:
#          port: 9999
#          logpath: /data/applogs/xxl-job/jobhandler
#          logretentiondays: 30



